### ISSUE TITLE
.ogg does not have a length

### ISSUE THREAD

**Issue by MrcSnm** [AuburnSounds/audio-formats#13] opened 2021-10-10 02:09 UTC
When loading a .ogg, `input.getLengthInFrames` returns -1.

**Comment by p0nce** [comment] 2021-10-10 14:25
Hello, can you provide the faulty WAV file? Cannot reproduce here.

**Comment by p0nce** [comment] 2021-10-10 15:01
Perhaps you mean an OGG?

**Comment by MrcSnm** [comment] 2021-10-10 15:03
> Perhaps you mean an OGG?

Yea, sorry for the mismatch

**Comment by p0nce** [comment] 2021-10-10 15:05
OK I can find that from the former OGG decoder, who had that.

**Comment by p0nce** [comment] 2021-10-10 19:52
Fixed in v1.3.5 with 65c17dd25de066ff827974a5c6b922c1c65d13ad

**Closed as completed by p0nce** 2021-10-10 19:52 UTC
Labels: bug
